In [1]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

<IPython.core.display.Javascript object>

# Numpy

Numpy (http://www.numpy.org/) is a Python software library providing support for the creation and manipulation of mult-dimensional arrays. These notes provide a brief overview of NumPy's features. More detail can be found in the NumPy Quickstart Tutorial.

*  https://docs.scipy.org/doc/numpy/user/quickstart.html

<h2 id="tocheading">Table of Contents</h2>
<div id="toc"></div>

## NumPy Arrays

The fundamental data type defined by NumPy is the `ndarray`, or multi-dimensional array, which itself defines several fields, among them: 

  * `ndarray.ndim` the number of dimensions defined by the array. 
  * `ndarray.shape`, a tuple of integers indicating the cardinality of each dimension. 
  * `ndarray.size`, the number of elements in the array. 
  * `ndarray.dtype`, the data type of the array elements (e.g., ints, floats, etc. ). 


## Creating Arrays

There are a number of way to create a new array, including arrays of 0s and 1s. There are also ways of creating new arrays by reshaping existing ones. 

In [2]:
import numpy as np

def describe_it(ar):
    """Print out a summary of an array."""
    print(f'dimensions: {ar.ndim}')
    print(f'shape: {ar.shape}')
    print(f'size: {ar.size}')
    print(f'dtype: {ar.dtype}')

line1 = [1,2,3]
line2 = [4,5,6]

array1 = np.array([line1,line2,line2]) # create a 2 x 3 array from the two lines. 

array2 = np.array((1,2,3,4,5), dtype=np.float64)  # create a 1x5 arrray of 64 bit floats. 

array3 = np.ones((2,2))  # create a 2x2 arrray of ones (floats, by default).

array4 = np.zeros((2,5), dtype=np.int16)  # create a 2x5 arrray of integer zeros. 

array5 = np.arange(10) # create an ndarray of 10 elements (0-9)

array6 = np.arange(0, 10, 0.5) # create an ndarray of 0 to 10 with step size of 0.5

array7 = np.linspace(0, 30, 10) # create an ndarray of 10 numbers in range [0,30] 

array8 = np.random.rand(2,3) # create a 2x3 array with random numbers taken from uniform dist. [0,1]

array9 =array4.reshape(1,10) # reshape array 4 into 1 row of 10. 

arrays = [array1, array2, array3, array4, array5, array6, array7, array8, array9]

for i in range(len(arrays)):
    array = arrays[i]
    print(f'Array {i}:')
    print('-'*40)
    print(array)
    describe_it(array)
    print('\n')
 

Array 0:
----------------------------------------
[[1 2 3]
 [4 5 6]
 [4 5 6]]
dimensions: 2
shape: (3, 3)
size: 9
dtype: int32


Array 1:
----------------------------------------
[1. 2. 3. 4. 5.]
dimensions: 1
shape: (5,)
size: 5
dtype: float64


Array 2:
----------------------------------------
[[1. 1.]
 [1. 1.]]
dimensions: 2
shape: (2, 2)
size: 4
dtype: float64


Array 3:
----------------------------------------
[[0 0 0 0 0]
 [0 0 0 0 0]]
dimensions: 2
shape: (2, 5)
size: 10
dtype: int16


Array 4:
----------------------------------------
[0 1 2 3 4 5 6 7 8 9]
dimensions: 1
shape: (10,)
size: 10
dtype: int32


Array 5:
----------------------------------------
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
dimensions: 1
shape: (20,)
size: 20
dtype: float64


Array 6:
----------------------------------------
[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]
dimensions: 1
shape:

## Numpy Arrays  don't mix datatypes

The elements of an array will have a common data type. E.g., it is not possible to create an array holding values of both `int` and `str`. However, it is possible to create an array using values of different types. If the values are all numerical, the NumPy might be able to use a common numerical datatype. The use of strings will results in an array consisting entirely of strings. 

In [3]:
data = np.array([1,2])
print('\nArray 1:')
for i in data:
    print(i,type(i))
    
data = np.array([1,2.0])
print('\nArray 2:')
for i in data:
    print(i,type(i))

data = np.array([1,"2"])
print('\nArray 3:')
for i in data:
    print(i,type(i))



Array 1:
1 <class 'numpy.int32'>
2 <class 'numpy.int32'>

Array 2:
1.0 <class 'numpy.float64'>
2.0 <class 'numpy.float64'>

Array 3:
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>


## Basic Operations


### Arithmetic Operations

Many basic arithmetic operations have been defined for arrays. Note that when, e.g., adding arrays of different types, **upscaling** occurs. 

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([1.0,0.0,1.0,0.0,1.0])

print('a + b:', a + b)    # element-wise addition
print('a - b:', a - b)    # element-wise subtraction
print('a * b:', a * b)    # element-wise product
print('a / b:', b / a)    # element-wise division
print('-'*40)

print('a + 10:', a + 10)   # scalar addition
print('a - 10:',a - 10)   # scalar subtraction
print('a * 10:',a * 10)   # scalar product
print('a / 10:',a / 10)   # scalar division
print('a ** 10:',a ** 2)   # scalar exponentiation

print('-'*40)
c = np.array([[1], [2], [3], [4], [5]])
print('a.c:',a.dot(c)) # dot product of a and c. 

print('-'*40,'\nstatistics over whole array (all elements)')

print('c min', c.min())
print('c max', c.max())
print('c sum', c.sum())
print('c mean', c.mean())

print('-'*40,'\nstatistics by axis')
d = np.array([[10,20], [30,40], [50,60], [70,80]])

print('d min (columns)', d.min(axis =0))
print('d min (rows)', d.min(axis =1))
print('d max (columns)', d.max(axis =0))
print('d max (rows)', d.max(axis =1))
print('d sum (columns)', d.sum(axis =0))
print('d sum (rows)', d.sum(axis =1))
print('d mean (columns)', d.mean(axis =0))
print('d mean (rows)', d.mean(axis =1))



a + b: [2. 2. 4. 4. 6.]
a - b: [0. 2. 2. 4. 4.]
a * b: [1. 0. 3. 0. 5.]
a / b: [1.         0.         0.33333333 0.         0.2       ]
----------------------------------------
a + 10: [11 12 13 14 15]
a - 10: [-9 -8 -7 -6 -5]
a * 10: [10 20 30 40 50]
a / 10: [0.1 0.2 0.3 0.4 0.5]
a ** 10: [ 1  4  9 16 25]
----------------------------------------
a.c: [55]
---------------------------------------- 
statistics over whole array (all elements)
c min 1
c max 5
c sum 15
c mean 3.0
---------------------------------------- 
statistics by axis
d min (columns) [10 20]
d min (rows) [10 30 50 70]
d max (columns) [70 80]
d max (rows) [20 40 60 80]
d sum (columns) [160 200]
d sum (rows) [ 30  70 110 150]
d mean (columns) [40. 50.]
d mean (rows) [15. 35. 55. 75.]



## Indexing and Slicing

We can access individual elements of arrays as well as "slices" using square brackets and `:`. 

In [5]:
a =  np.arange(50).reshape(5,10) 

print('-'*40)
print("array:")
print(a)
print('-'*40)
print("first row:")
print(a[0]) 
print('-'*40)
print("rows 2-4")
print(a[2:]) 
print('-'*40)
print("2nd element of 2nd row")
print(a[1,1])
print('-'*40)
print("every element of column 4")
print(a[:,4])
print('-'*40)
print("every element of columns 2 and 3")
print(a[:,2:4])

----------------------------------------
array:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
----------------------------------------
first row:
[0 1 2 3 4 5 6 7 8 9]
----------------------------------------
rows 2-4
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
----------------------------------------
2nd element of 2nd row
11
----------------------------------------
every element of column 4
[ 4 14 24 34 44]
----------------------------------------
every element of columns 2 and 3
[[ 2  3]
 [12 13]
 [22 23]
 [32 33]
 [42 43]]


In [6]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[0:10:3]) # Note the step size of 3

[ 1  4  7 10]


## Dot notation: `...`

In a multidimensional array, `...` can be used to stand for multiple instances of `:`, enough to form a complete index in an expression. 

In [7]:
a = np.arange(27).reshape(3,3,3) # create a 3x3x3 array with ints 0-26

print('-'*40)
print(a)
print('-'*40)
print("first: ")
print(a[1,...]) # same as a[1,:,:]

print('-'*40)
print("second: ")
print(a[1,1,...]) # same as a[1,1,:]
print('-'*40)
print("third: ")
print(a[...,2]) # same as a[:,:,2]


----------------------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
----------------------------------------
first: 
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
----------------------------------------
second: 
[12 13 14]
----------------------------------------
third: 
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


## Iterating and flattening

Iterating over all elemetns of a multidimensional array is easy, and there is a builtin method for flattening an array. 

In [8]:
a = np.arange(30).reshape(3,10) 
print(a)
print('-'*40)
# to iterate over each element in a 2D array. 
for e in a.flat:
    print(e,end=' ')

print()
print('-'*40)

# alternatively, flatten beforehand
b = a.flatten()
for e in b:
    print(e,end=' ')
    


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
----------------------------------------
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 
----------------------------------------
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 

## Reshaping, Recomposition

As noted earlier, arrays can be reshaped using `reshape`. To transpose an array, use `.T`.

In [9]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print("a")
print(a)
print('-'*40)
print("a reshaped")
print(a.reshape(2,2,2))
print('-'*40)
print("a transposed")
print(a.T)


a
[[1 2 3 4]
 [5 6 7 8]]
----------------------------------------
a reshaped
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
----------------------------------------
a transposed
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


Arrays can also be combined, or "stacked".

In [10]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.array([11,12,13,14,15])
d = np.vstack((a,b,c))
print(d)
print('-'*40)
e = np.hstack((a,b,c))
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
----------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## Deep and Shallow Copying

Some operations return a new array composed of the very same (in memory) elements of another array, though rearranged. Other operations return an array that contains copies of the elements. Still other operations manipulate the original array but do not make a copy. 

Knowing when each of these occurs is very important, especially when manipulating large amounts of data, but it is not always easy to discern which has occurred. In general, however:

*  **variable assignments** (i.e., assigning an array to a variable) do not copy array objects. 
*  **function calls** using arrays as arguments do not result in a copy of the array (merely a reference to the array is passed). 
*  **arithmetic operations** on arrays generally produce new arrays. Altering the new array does not alter the orginal. 
*  **slicing** an array creates a **view** (a shallow copy) of an array. The two arrays share elements, so that changing an element in one changes the other. 



In [11]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b = a[:,0:3]  # create a slice of a and stored it in b. 
c = b.copy() # create a deep copy of b. 
b[0,0] = 100 # this will change a, too. 
c[0,0] = 300 # this won't change a or b. 
a[1,2] = 200 # this will change b, too. 
print("a")
print(a)
print('-'*40)
print("b")
print(b)
print('-'*40)
print("c")
print(c)

a
[[100   2   3   4]
 [  5   6 200   8]]
----------------------------------------
b
[[100   2   3]
 [  5   6 200]]
----------------------------------------
c
[[300   2   3]
 [  5   6   7]]


The below illustrates that arithmetic operations yield copies. 

In [12]:
a = np.array([1,2,3,4,5])
b = a + 10
c = b * 10
b[0] = 100
print('a', a)
print('b', b)
print('c', c)

a [1 2 3 4 5]
b [100  12  13  14  15]
c [110 120 130 140 150]


Note that altering b has no affect on a, even b is the result of a scalar addition on a.  